/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import Dao.CommandeDao;
import Dao.MenuDao;
import Dao.PayementDao;
import Dao.TablesDao;
import Modele.FactureModele;
import Modele.MenuModele;
import Modele.PayementModele;
import Modele.TablesModele;
import controller.CommanderController;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static controller.Verif.dash;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author Hery
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu() throws SQLException{
        initComponents();
        show();
        listeComande();
        JScrollPane scroll = new JScrollPane(jPanel1);
        this.add(scroll);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPayer = new javax.swing.JButton();
        panneau = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        numtabl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labtotalPrix = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        numTable = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setAutoscrolls(true);

        jPanel2.setBackground(new java.awt.Color(253, 236, 236));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPayer.setBackground(new java.awt.Color(0, 153, 0));
        btnPayer.setText("Payer");
        btnPayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayerActionPerformed(evt);
            }
        });
        jPanel2.add(btnPayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 690, 130, -1));

        panneau.setBackground(new java.awt.Color(253, 236, 236));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(253, 236, 236));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("RESTAURENT  LaurAndr");

        numtabl.setForeground(new java.awt.Color(0, 0, 51));
        numtabl.setText("table:");

        javax.swing.GroupLayout panneauLayout = new javax.swing.GroupLayout(panneau);
        panneau.setLayout(panneauLayout);
        panneauLayout.setHorizontalGroup(
            panneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneauLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(96, 96, 96))
            .addGroup(panneauLayout.createSequentialGroup()
                .addGroup(panneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panneauLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(numtabl))
                    .addGroup(panneauLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panneauLayout.setVerticalGroup(
            panneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneauLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(numtabl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(panneau, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 350, 650));

        jLabel1.setText("Total:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, -1, 30));

        labtotalPrix.setText("0");
        jPanel2.add(labtotalPrix, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, 130, 30));

        jPanel3.setBackground(new java.awt.Color(51, 0, 204));

        numTable.setForeground(new java.awt.Color(12, 12, 12));
        numTable.setText("jLabel1");
        jPanel3.add(numTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayerActionPerformed

        PayementDao paye = new PayementDao();
        TablesDao tab = new TablesDao();
        CommandeDao com = new CommandeDao();
        TablesModele tabMod = new TablesModele();
        tabMod.setId(Integer.parseInt(TableItem.numeroTable));
        tabMod.setEtat("libre");
        tab.updateTable(tabMod);
        com.updateEtatCommande(TableItem.numeroCommande,"paye");

        try {
            int total = com.totalFact(TableItem.numeroCommande);
                PayementModele modele = new PayementModele();
                modele.setIdCommande(TableItem.numeroCommande);
                modele.setMontant(total);
               // paye.payer(modele);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Toolkit kiToolkit = Toolkit.getDefaultToolkit();
            PrintJob pj = kiToolkit.getPrintJob(dash,"impression",null);
            Graphics g = pj.getGraphics();
            panneau.printAll(g);
            pj.end();
        
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e," erreur",JOptionPane.ERROR_MESSAGE);
        }
        Tables t = new Tables();
        dash.aseovo(t);
        
    }//GEN-LAST:event_btnPayerActionPerformed

    public void show(){
        try {
            MenuDao menu = new MenuDao();
            numTable.setText("Table"+TableItem.numeroTable);
            numtabl.setText("Table:"+TableItem.numeroTable);
            List<MenuModele> listee = menu.listePlat();
            for(MenuModele l : listee){
                Item item = new Item();   
                item.setPreferredSize(new Dimension(250,300));
                item.setVisible(true);
                item.setImage("/images/"+l.getPhoto());
                item.nomp.setText(l.getNom());
                item.p.setText(""+l.getPrix());
                item.labidmenu.setText(""+l.getId());
                item.reste.setText(""+l.getDisponible());
                jPanel1.add(item); 
                CommanderController cmd = new CommanderController(item);
                item.btnCommande.addActionListener(cmd);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void listeComande() throws SQLException{
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Nom","Quantiter","Total"
            }
        ));
        DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
        CommandeDao com = new CommandeDao();
        int idComm = TableItem.numeroCommande;
        List<FactureModele> comall = com.toutCommande(idComm);
        int somme = 0;
        for(FactureModele factmod:comall){
            somme += factmod.getTotalP();
            mod.addRow(new Object[]{factmod.getNom(),factmod.getQuantite(),factmod.getTotalP()});
        }
        labtotalPrix.setText(String.valueOf(somme)+" Ar");
        
//        jTable1.setValueAt("Numero", 0,0);

    }
    public view.Item item;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnPayer;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    public javax.swing.JLabel labtotalPrix;
    public javax.swing.JLabel numTable;
    public javax.swing.JLabel numtabl;
    public javax.swing.JPanel panneau;
    // End of variables declaration//GEN-END:variables
}
