/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import Dao.TablesDao;
import Modele.TablesModele;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author Hery
 */
public class Tables extends javax.swing.JPanel {

    /**
     * Creates new form Tables
     */
    public Tables() {
        initComponents();
        show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
    @Override
    public void show(){
         TablesDao tables = new TablesDao();
            List<TablesModele> listee;
        try {
            listee = tables.listeTable();
            for(TablesModele l : listee){
                tab = new view.TableItem();
                tab.setVisible(true);
                tab.jButton1.setText(""+l.getNumero());
                if (l.getEtat().equalsIgnoreCase("occuper")) {
                    tab.jButton1.setBackground(new java.awt.Color(25, 23, 25));

                }
                add(tab);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Tables.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    
    }
    public view.TableItem tab;
    public view.Menu menu;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
