/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import Dao.CommandeDao;
import Dao.TablesDao;
import Modele.TablesModele;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import static controller.Verif.dash;
/**
 *
 * @author Hery
 */
public class TableItem extends javax.swing.JPanel {

    /**
     * Creates new form TableItem
     */
    public TableItem() {
        initComponents();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setText("table");
        jButton1.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        numeroTable = jButton1.getText();
        TablesDao d = new TablesDao();
        CommandeDao c = new CommandeDao();
        try {
            boolean etatTab = d.verifTable(Integer.parseInt(numeroTable));
            if(etatTab){
                c.commander(Integer.parseInt(numeroTable));
                numeroCommande = c.numeroCommande(Integer.parseInt(numeroTable));
            } else {
                numeroCommande = c.numeroCommande(Integer.parseInt(numeroTable));
            }
            
            menu = new Menu();
        } catch (SQLException ex) {
            Logger.getLogger(TableItem.class.getName()).log(Level.SEVERE, null, ex);
        }
        TablesModele tabMod = new TablesModele();
        tabMod.setId(Integer.parseInt(numeroTable));
        tabMod.setEtat("occuper");
        d.updateTable(tabMod);
        dash.aseovo((JPanel) menu);
    }//GEN-LAST:event_jButton1ActionPerformed
    public view.Menu menu;
    public static String numeroTable;
    public static int numeroCommande;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
